### ISSUE TITLE
Anonymous users does not have storage.objects.get access to

### ISSUE THREAD

**Issue by seldimi** [Superbalist/laravel-google-cloud-storage#20] opened 2017-11-15 17:08 UTC
Hello. 
Can you guide me on how do we solve such issues? Files uploaded correctly, but URL gives the following error

Anonymous users does not have storage.objects.get access to ....

**Comment by zoidbergwill** [comment] 2017-11-15 20:50
Have you tried changing the visibility of the file after uploading it?

```
    /**
     * {@inheritdoc}
     */
    public function setVisibility($path, $visibility)
    {
        $object = $this->getObject($path);

        if ($visibility === AdapterInterface::VISIBILITY_PRIVATE) {
            $object->acl()->delete('allUsers');
        } elseif ($visibility === AdapterInterface::VISIBILITY_PUBLIC) {
            $object->acl()->add('allUsers', Acl::ROLE_READER);
        }

        $normalised = $this->normaliseObject($object);
        $normalised['visibility'] = $visibility;

        return $normalised;
    }
```

**Comment by zoidbergwill** [comment] 2017-11-15 20:50
The default seems to be private, unless you change it for the whole bucket.

**Comment by zoidbergwill** [comment] 2017-11-30 14:56
Closing as a dupe of https://github.com/Superbalist/laravel-google-cloud-storage/issues/8

**Closed by zoidbergwill** 2017-11-30 14:56 UTC
